language: node_js
node_js: 
 - '12'

cache:
  directories:
    - node_modules
  npm: true

before_install:
  - npm install

jobs:
  include:
    - stage: test
      name: test
      script:
        - npm run build
        - npm run test
