language: node_js
node_js: 
 - '12'

cache:
  directories:
    - node_modules
  npm: true

before_install:
  - sudo apt-get -y install libxml2-dev
  - npm install

addons:
  apt:
    update: true


jobs:
  include:
    - stage: test
      name: test
      script:
        - npm run test
